name: Docker CI/CD Pipeline
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker images
        run: |
          docker compose build
      - name: Start app service
        run: |
          docker compose up -d app
      - name: Wait for app to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:8000/items 2>/dev/null; do sleep 2; done'
      - name: Run tests
        run: |
          ./run_tests.sh
      - name: Cleanup
        run: |
          docker compose down
